"""ToolAgents-backed model/runtime harness for GRC Agent."""

from __future__ import annotations

import copy
import datetime
import json
import logging
import os
import threading
import uuid
from collections.abc import Callable, Generator, Iterator
from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING, Any

import httpx as _httpx
from openai import APIConnectionError, OpenAI
from ToolAgents import FunctionTool, ToolRegistry
from ToolAgents.agents import ChatToolAgent
from ToolAgents.data_models.chat_history import ChatHistory
from ToolAgents.data_models.messages import (
    ChatMessage,
    ChatMessageRole,
    TextContent,
    ToolCallContent,
    ToolCallResultContent,
)
from ToolAgents.provider import OpenAIChatAPI
from ToolAgents.provider.llm_provider import ProviderSettings

from grc_agent.chat_roles import (
    ASSISTANT_MODEL_ROLE,
    TOOL_MODEL_ROLE,
    USER_MODEL_ROLE,
    chat_message_payload,
)
from grc_agent.domain_models import ErrorCode, build_error_payload
from grc_agent.runtime.model_context import MVP_TOOL_SURFACE

logger = logging.getLogger(__name__)


if TYPE_CHECKING:
    from grc_agent.agent import GrcAgent


# Catches the OpenAI SDK's ``APIConnectionError`` (the one bubbled up by
# ``openai.OpenAI`` chat completions) as well as the underlying ``httpx``
# transport errors that surface from a missing local Ollama/OpenRouter
# endpoint. Kept as a tuple so the runner can ``except (_BACKEND_...)``
# once and stay flat against the SDK version.
_BACKEND_CONNECTION_ERRORS = (
    APIConnectionError,
    _httpx.ConnectError,
    _httpx.ConnectTimeout,
    _httpx.ReadTimeout,
)


def _backend_unreachable_hint(server_url: str) -> str:
    """Return the platform-agnostic hint shown to the user.

    No ``systemctl`` / ``journalctl`` / Linux-specific text. Applies on
    macOS and Windows where Ollama is a desktop application that the
    user starts from the menu bar / Start menu. The string is a fact
    (refused connection at URL) — no in-band behavioral directives.
    """
    return f"Connection refused at {server_url}."


# Factual synthesized text used when the model returns empty content and no
# tool calls on every retry attempt of a turn (scenario 01: "empty final
# text"). A plain fact — no behavioral command, no ALL-CAPS directive, no
# procedural recipe (AGENTS.md "no in-band control flow").
_EMPTY_MODEL_RESPONSE_TEXT = "No response was generated by the model."


# Factual note injected (user-role, runtime-directive wrapped) when the model
# re-sends a byte-identical failing change_graph batch. Purely informational —
# no behavioral command or procedural recipe (AGENTS.md "no in-band control
# flow"); the system prompt remains the only behavioral authority.
_LOOP_NOTE = (
    "<runtime_directive>\n"
    "The last tool call used arguments identical to a previous failed attempt "
    "this turn and produced the same error. Repeating unchanged arguments will "
    "not change the result.\n"
    "</runtime_directive>"
)

# Loop-detection thresholds for a model re-sending byte-identical failing
# tool-call arguments within one turn (see ``_call_signature``/``_LOOP_NOTE``
# above). On the warn threshold, inject a factual note once; on the stop
# threshold, abandon the turn instead of burning the whole tool budget.
_LOOP_WARN_THRESHOLD = 2
_LOOP_STOP_THRESHOLD = 3

# Per-attempt retries for one model "step" call when the response is
# transiently degenerate (empty content + no tool calls) or the backend
# connection drops — see ``_BACKEND_CONNECTION_ERRORS`` above.
_MAX_PROVIDER_RETRIES = 3


# -- OpenRouter web-search plugin (request-side augmentation) ---------------
#
# OpenRouter has no standalone web-search REST endpoint. Web search is a
# request-side plugin: ``extra_body["plugins"] = [{"id": "web", ...}]`` grounds
# the model's answer with live results and OpenRouter returns ``url_citation``
# annotations on the assistant message (surfaced by GrcResponseConverter).
# On by default for the OpenRouter backend; opt out with OPENROUTER_WEB_SEARCH=false.
# The Ollama backend never reads these — its web_search/web_fetch tools hit
# Ollama's own hosted API (fully separate path).

# Model-facing tools bound to the Ollama backend. On OpenRouter the `web`
# plugin replaces them, so they are dropped from the surfaced tool set there.
_OLLAMA_ONLY_TOOLS: frozenset[str] = frozenset({"web_search", "web_fetch"})


def _env_truthy(var: str, *, default: bool) -> bool:
    raw = os.getenv(var)
    if raw is None:
        return default
    return raw.strip().lower() in ("true", "1", "yes", "on")


def _env_int_clamped(var: str, *, default: int, lo: int, hi: int) -> int:
    raw = os.getenv(var)
    if raw is None or not raw.strip():
        return default
    try:
        value = int(raw)
    except ValueError:
        return default
    return max(lo, min(value, hi))


def _env_csv(var: str) -> list[str] | None:
    raw = os.getenv(var)
    if not raw:
        return None
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    return parts or None


def _openrouter_web_plugin() -> dict[str, Any] | None:
    """Build the OpenRouter ``web`` plugin config from env, or None when off."""
    if not _env_truthy("OPENROUTER_WEB_SEARCH", default=True):
        return None
    plugin: dict[str, Any] = {
        "id": "web",
        "max_results": _env_int_clamped(
            "OPENROUTER_WEB_SEARCH_MAX_RESULTS", default=5, lo=1, hi=10
        ),
    }
    include = _env_csv("OPENROUTER_WEB_SEARCH_INCLUDE_DOMAINS")
    exclude = _env_csv("OPENROUTER_WEB_SEARCH_EXCLUDE_DOMAINS")
    if include:
        plugin["include_domains"] = include
    if exclude:
        plugin["exclude_domains"] = exclude
    return plugin


def _call_signature(arguments: Any) -> str:
    """Canonical signature for a tool call's arguments.

    Used to detect a model re-sending a byte-identical failing call — the
    cause of every safety-ceiling failure in the agent_flow review
    (scenarios 06/15/17). Identical arguments + identical failure ⇒ the model
    is stuck and the turn budget is being wasted. One uniform rule for every
    tool, not a per-tool special-case.
    """
    try:
        return json.dumps(arguments, sort_keys=True, default=str)
    except (TypeError, ValueError):
        return str(arguments)


def _backend_unreachable_payload(
    *,
    exc: BaseException,
    model: str,
    server_url: str,
    assistant_turns: int = 0,
) -> dict[str, Any]:
    """Build the typed result returned when the backend is unreachable."""
    hint = _backend_unreachable_hint(server_url)
    payload = build_error_payload(
        error_type=ErrorCode.BACKEND_UNREACHABLE,
        message=hint,
        details={
            "server_url": server_url,
            "exception_type": type(exc).__name__,
        },
    )
    payload["model"] = model
    payload["steps"] = assistant_turns
    payload["tool_rounds_used"] = 0
    payload["tool_calls_requested"] = 0
    payload["tool_calls_executed"] = 0
    payload["assistant_text"] = hint
    return payload


class GrcOpenAIChatAPI(OpenAIChatAPI):
    """OpenAI-compatible provider.

    Delegates ``get_response``/``get_streaming_response`` to the parent,
    which calls ``self.client.chat.completions.create(**request_kwargs)``.
    The OpenAI SDK natively supports OpenAI-compatible backends (Ollama,
    OpenRouter) via ``base_url`` and forwards ``extra_body`` (used by
    OpenRouter routing controls set in ``create_settings``).
    """

    def __init__(
        self,
        *,
        api_key: str,
        model: str,
        base_url: str,
        timeout_seconds: float,
    ) -> None:
        super().__init__(api_key=api_key, model=model, base_url=base_url)
        self.api_key = api_key
        self.timeout_seconds = timeout_seconds
        self.client = OpenAI(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout_seconds,
        )
        self.response_converter = GrcResponseConverter(self.response_converter)



class GrcResponseConverter:
    """Wrapper converter to extract and prepend thinking tokens.

    The OpenAI SDK does not standardize a thinking field name. Each
    provider puts reasoning on its own attribute:

    - **Ollama OpenAI-compat endpoint** (``/v1/chat/completions``):
      ``delta.reasoning`` and ``message.reasoning``
    - **Native Ollama chat API** (``/api/chat``): ``message.thinking``
    - **OpenRouter DeepSeek / Claude / etc.**: ``delta.reasoning_content``
      and ``message.reasoning_content``

    The wrapper checks all three in priority order so a single converter
    works for every backend without per-provider branching.
    """

    _THINKING_FIELDS = ("reasoning", "reasoning_content", "thinking")

    def __init__(self, parent_converter: Any) -> None:
        self.parent_converter = parent_converter

    @classmethod
    def _extract_thinking(cls, obj: Any) -> str | None:
        """Return the first non-empty thinking value from any supported field.

        Inspects the object's attributes first (Pydantic SDK delta/message
        models); falls back to ``model_extra`` for fields the SDK doesn't
        declare (Ollama, custom OpenRouter models).
        """
        for field in cls._THINKING_FIELDS:
            value = getattr(obj, field, None)
            if value:
                return value
        model_extra = getattr(obj, "model_extra", None)
        if model_extra:
            for field in cls._THINKING_FIELDS:
                value = model_extra.get(field)
                if value:
                    return value
        return None

    @classmethod
    def _extract_url_citations(cls, obj: Any) -> list[dict[str, str]]:
        """Collect ``url_citation`` annotations from a message or delta.

        Works for both non-streaming ``choice.message`` and streaming
        ``choice.delta`` — the OpenAI SDK declares ``annotations`` on both.
        Returns ``[{title, url, content?}]`` in encounter order.

        OpenRouter's ``web`` plugin returns these annotations; without
        surfacing them the model's web grounding is invisible to the user.
        """
        raw: Any = getattr(obj, "annotations", None)
        if not raw:
            model_extra = getattr(obj, "model_extra", None)
            if model_extra:
                raw = model_extra.get("annotations")
        if not raw:
            return []
        out: list[dict[str, str]] = []
        for ann in raw:
            if getattr(ann, "type", None) != "url_citation":
                continue
            citation = getattr(ann, "url_citation", None) or ann
            url = getattr(citation, "url", None)
            if url is None and isinstance(citation, dict):
                url = citation.get("url")
            if not url:
                continue
            title = (
                getattr(citation, "title", None)
                or (citation.get("title") if isinstance(citation, dict) else None)
                or url
            )
            content = (
                getattr(citation, "content", None)
                or (citation.get("content") if isinstance(citation, dict) else None)
                or ""
            )
            entry: dict[str, str] = {"title": title, "url": url}
            if content:
                entry["content"] = content
            out.append(entry)
        return out

    @staticmethod
    def _render_citations_footnote(citations: list[dict[str, str]]) -> str:
        """Render a ``Sources:`` markdown footnote, or ``""`` when empty."""
        if not citations:
            return ""
        lines = ["", "Sources:"]
        for c in citations:
            title = c.get("title") or c.get("url") or "source"
            url = c.get("url")
            lines.append(f"- [{title}]({url})" if url else f"- {title}")
        return "\n".join(lines)

    def from_provider_response(self, response_data: Any) -> ChatMessage:
        chat_message = self.parent_converter.from_provider_response(response_data)
        if hasattr(response_data, "choices") and response_data.choices:
            choice = response_data.choices[0]
            reasoning_content = self._extract_thinking(choice.message)

            if reasoning_content:
                text_content = None
                for content in chat_message.content:
                    if isinstance(content, TextContent) and isinstance(content.content, str):
                        text_content = content
                        break

                think_tag_block = f"<think>{reasoning_content}</think>\n"
                if text_content is not None:
                    text_content.content = think_tag_block + text_content.content
                else:
                    chat_message.content.insert(0, TextContent(content=think_tag_block))

            footnote = self._render_citations_footnote(self._extract_url_citations(choice.message))
            if footnote:
                text_content = None
                for content in chat_message.content:
                    if isinstance(content, TextContent) and isinstance(content.content, str):
                        text_content = content
                        break
                if text_content is not None:
                    text_content.content = text_content.content.rstrip() + "\n" + footnote
                else:
                    chat_message.content.append(TextContent(content=footnote))

        return chat_message

    def __getattr__(self, name: str) -> Any:
        return getattr(self.parent_converter, name)


@dataclass
class ToolAgentsLlamaProviderConfig:
    """Configuration for the ToolAgents OpenAI-compatible provider."""

    base_url: str
    model: str = ""
    api_key: str | None = None
    timeout_seconds: float = 60.0
    max_tokens: int = 4096
    backend: str = "ollama"
    max_tool_rounds: int = 8

    def __post_init__(self) -> None:
        if self.backend == "ollama" and "openrouter" in (self.base_url or "").lower():
            self.backend = "openrouter"

    @property
    def openai_base_url(self) -> str:
        base = self.base_url.rstrip("/")
        if base.endswith("/v1"):
            return base
        return f"{base}/v1"

    def create_provider(self) -> GrcOpenAIChatAPI:
        """Create the ToolAgents OpenAI-compatible provider."""
        return GrcOpenAIChatAPI(
            api_key=self.api_key or "not-needed",
            model=self.model,
            base_url=self.openai_base_url,
            timeout_seconds=self.timeout_seconds,
        )

    def create_settings(
        self,
        provider: GrcOpenAIChatAPI,
        *,
        tool_choice: str | dict[str, Any] = "auto",
        response_format: dict[str, Any] | None = None,
        max_tokens: int | None = None,
    ) -> ProviderSettings:
        """Return request settings."""
        settings = provider.get_default_settings()
        settings.set_value("tool_choice", tool_choice)
        settings.set_value("response_format", response_format)
        settings.add_request_setting("max_tokens", max_tokens or self.max_tokens)
        settings.add_request_setting("parallel_tool_calls", True)
        # Ask for a final usage chunk on the stream so the GUI can show real
        # token/context usage measured from the response, not an estimate.
        # Production always streams via stream_step.
        settings.add_request_setting("stream_options", {"include_usage": True})
        extra_body: dict[str, Any] = {}
        is_openrouter = self.backend == "openrouter"
        is_ollama = self.backend == "ollama"
        if is_ollama:
            extra_body["think"] = True
        if is_openrouter:
            provider_order = os.getenv("OPENROUTER_PROVIDER_ORDER")
            allow_fallbacks = os.getenv("OPENROUTER_ALLOW_FALLBACKS")

            provider_dict: dict[str, Any] = {}
            if provider_order:
                provider_dict["order"] = [p.strip() for p in provider_order.split(",") if p.strip()]
            if allow_fallbacks is not None:
                provider_dict["allow_fallbacks"] = allow_fallbacks.lower() in ("true", "1", "yes")

            if provider_dict:
                extra_body["provider"] = provider_dict

            web_plugin = _openrouter_web_plugin()
            if web_plugin is not None:
                extra_body["plugins"] = [web_plugin]

        if extra_body:
            settings.set_value("extra_body", extra_body)
        return settings


@dataclass(frozen=True)
class ToolDelegateResult:
    """Result of executing a ToolAgents-requested wrapper."""

    result: dict[str, Any]
    executed: bool


class ToolAgentsToolDelegate:
    def __init__(
        self,
        agent: GrcAgent,
        tool_name: str,
        *,
        on_tool_start: Callable[[str, dict[str, Any]], None] | None = None,
        on_tool_end: Callable[[str, Any], None] | None = None,
    ) -> None:
        self.agent = agent
        self.tool_name = tool_name
        self.on_tool_start = on_tool_start
        self.on_tool_end = on_tool_end

    def invoke(
        self,
        arguments: Any,
        *,
        allowed_tool_names: set[str] | tuple[str, ...] | None = None,
    ) -> ToolDelegateResult:
        """Validate route/schema before executing the underlying GRC wrapper."""
        normalized = self.agent.normalize_tool_call_arguments(
            self.tool_name,
            arguments,
            model_tool_call=True,
        )
        route_result = self.agent.validate_turn_route(
            self.tool_name,
            normalized,
            allowed_tool_names=allowed_tool_names,
        )
        validation_result = (
            route_result
            if route_result is not None
            else self.agent.validate_tool_call(
                self.tool_name,
                normalized,
                model_tool_call=True,
            )
        )
        if validation_result is not None:
            return ToolDelegateResult(result=validation_result, executed=False)

        # Trigger tool start callback
        if self.on_tool_start:
            try:
                self.on_tool_start(self.tool_name, normalized)
            except Exception as e:
                logger.error(f"Error in on_tool_start callback: {e}")

        result = self.agent.execute_tool(
            self.tool_name,
            normalized,
            model_tool_call=True,
        )

        # Trigger tool end callback
        if self.on_tool_end:
            try:
                self.on_tool_end(self.tool_name, result)
            except Exception as e:
                logger.error(f"Error in on_tool_end callback: {e}")

        return ToolDelegateResult(result=result, executed=True)


class ToolAgentsRegistryBuilder:
    """Build a ToolAgents registry from the current GRC turn schemas."""

    def __init__(
        self,
        agent: GrcAgent,
        *,
        on_tool_start: Callable[[str, dict[str, Any]], None] | None = None,
        on_tool_end: Callable[[str, Any], None] | None = None,
    ) -> None:
        self.agent = agent
        self.on_tool_start = on_tool_start
        self.on_tool_end = on_tool_end
        self.delegates: dict[str, ToolAgentsToolDelegate] = {}

    def build(
        self,
        allowed_tool_names: set[str] | tuple[str, ...] | None = None,
    ) -> ToolRegistry:
        registry = ToolRegistry()
        self.delegates = {}
        for schema in self.agent.get_tool_schemas_for_turn(allowed_tool_names):
            name = str(schema["function"]["name"])
            delegate = ToolAgentsToolDelegate(
                self.agent,
                name,
                on_tool_start=self.on_tool_start,
                on_tool_end=self.on_tool_end,
            )
            registry.add_tool(_function_tool_from_openai_tool(schema, delegate))
            self.delegates[name] = delegate
        return registry


@dataclass(frozen=True)
class _ToolDispatchOutcome:
    """Result of one tool-dispatch round inside ``_run_turn_events``."""

    executed_count: int
    loop_stuck: bool


class _LoopDecision(Enum):
    """Outcome of ``_evaluate_loop_state`` for one tool call."""

    CONTINUE = "continue"
    WARN = "warn"
    STOP = "stop"


class ToolAgentsRunner:
    """Bounded model turn runner using ToolAgents step calls."""

    def __init__(
        self,
        provider_config: ToolAgentsLlamaProviderConfig,
        *,
        chat_agent: ChatToolAgent | None = None,
    ) -> None:
        self.provider_config = provider_config
        self.provider = (
            chat_agent.chat_api if chat_agent is not None else provider_config.create_provider()
        )
        self.chat_agent = chat_agent or ChatToolAgent(chat_api=self.provider)

    def run_turn(
        self,
        agent: GrcAgent,
        user_message: str,
        *,
        model: str | None = None,
        max_tool_rounds: int | None = None,
        on_tool_start: Callable[[str, dict[str, Any]], None] | None = None,
        on_tool_end: Callable[[str, Any], None] | None = None,
        cancel_event: threading.Event | None = None,
    ) -> dict[str, Any]:
        """Run one bounded ToolAgents-backed model turn.

        Returns the same dict shape as ``stream_turn``'s final event, for
        callers that want a single blocking call. The internal loop
        yields events through ``_run_turn_events``; this method consumes
        them and assembles the structured result.
        """
        if not isinstance(user_message, str) or not user_message.strip():
            raise ValueError("user_message must be a non-empty string.")

        for event in self._run_turn_events(
            agent,
            user_message,
            model=model,
            max_tool_rounds=max_tool_rounds,
            on_tool_start=on_tool_start,
            on_tool_end=on_tool_end,
            cancel_event=cancel_event,
        ):
            if event.get("event") == "final":
                return event.get("result", {})
        payload = build_error_payload(
            error_type=ErrorCode.NO_FINAL,
            message="Turn loop ended without a final event.",
        )
        payload["assistant_text"] = "Turn loop ended without a final event."
        return payload

    def stream_turn(
        self,
        agent: GrcAgent,
        user_message: str,
        *,
        model: str | None = None,
        max_tool_rounds: int | None = None,
        on_tool_start: Callable[[str, dict[str, Any]], None] | None = None,
        on_tool_end: Callable[[str, Any], None] | None = None,
        cancel_event: threading.Event | None = None,
    ) -> Iterator[dict[str, Any]]:
        """Yield events from one bounded turn. Same loop as ``run_turn``.

        ``cancel_event`` (optional, ``threading.Event``-like) is checked
        cooperatively inside ``_fetch_model_response``'s stream loop.
        When set, the in-flight provider stream is closed cleanly,
        whatever partial message has been accumulated is persisted to
        ``agent.chat_history`` and emitted as one ``assistant_model``
        SSOT event before returning.  No hard-kill of the HTTP client.

        Events:

        * ``{"event": "chunk", "text": "..."}`` — model output chunk.
          Emitted with real provider streaming when the final assistant
          message has no tool calls; emitted in one chunk otherwise.
        * ``{"event": "tool_start", "name": "..."}`` — pre-tool hook.
        * ``{"event": "tool_end", "name": "...", "result": {...}}`` —
          post-tool hook.
        * ``{"event": "model_message", "role": "...", "payload": {...}}``
          — typed ``ChatMessage`` added to ``agent.chat_history`` during
          the turn. ``role`` is ``assistant_model`` or ``tool_model``.
        * ``{"event": "final", "result": {...}}`` — terminal structured
          result, same shape as ``run_turn``'s return value.
        """
        yield from self._run_turn_events(
            agent,
            user_message,
            model=model,
            max_tool_rounds=max_tool_rounds,
            on_tool_start=on_tool_start,
            on_tool_end=on_tool_end,
            cancel_event=cancel_event,
        )

    # ------------------------------------------------------------------ #
    # _run_turn_events helpers (structural decomposition — no logic change)
    # ------------------------------------------------------------------ #

    def _evaluate_loop_state(
        self,
        tool_name: str,
        tool_call_arguments: Any,
        result: Any,
        executed: bool,
        failing_call_signatures: dict[tuple[str, str], int],
    ) -> _LoopDecision:
        """Return CONTINUE / WARN / STOP for one tool call.

        Mutates ``failing_call_signatures`` in place.  Logic-identical to
        the inline checks previously embedded in the tool-dispatch loop.
        """
        if not (executed and isinstance(result, dict) and result.get("ok") is False):
            return _LoopDecision.CONTINUE
        sig = _call_signature(tool_call_arguments)
        key = (tool_name, sig)
        failing_call_signatures[key] = failing_call_signatures.get(key, 0) + 1
        count = failing_call_signatures[key]
        if count == _LOOP_WARN_THRESHOLD:
            return _LoopDecision.WARN
        if count >= _LOOP_STOP_THRESHOLD:
            return _LoopDecision.STOP
        return _LoopDecision.CONTINUE

    def _fetch_model_response(
        self,
        agent: GrcAgent,
        registry: ToolRegistry,
        settings: ProviderSettings,
        resolved_model: str,
        assistant_turns: int,
        cancel_event: threading.Event | None = None,
    ) -> Generator[dict[str, Any], None, tuple[ChatMessage, bool] | None]:
        """Run the provider-retry loop and stream-consume ``stream_step``.

        Yields ``{"event": "chunk", ...}`` during streaming, and on
        backend-unreachable yields the assistant_model + final events,
        then ``return``s ``None`` to signal the caller to terminate.

        Returns ``(assistant_message, streamed_any_content)`` on success,
        ``None`` after the unreachable final has already been emitted,
        and ``None`` (with a ``assistant_model`` event already yielded)
        on cooperative cancel — the caller checks ``fetched is None``
        and terminates the turn.

        ``cancel_event`` is checked between chunks. When set, the
        in-flight stream is abandoned cleanly (the Python generator
        from ``stream_step`` runs to exhaustion or breaks naturally);
        whatever assistant message was being assembled is appended to
        ``agent.chat_history`` with a "cancelled" note, emitted as one
        ``assistant_model`` SSOT event, and we return ``None``.
        """
        retry_attempts = _MAX_PROVIDER_RETRIES
        for attempt in range(retry_attempts):
            system_salt = None
            if attempt > 0:
                system_salt = f"retry_salt: {uuid.uuid4()}"

            messages = agent.get_model_messages(system_salt=system_salt)
            try:
                streamed_any_content = False
                assistant_message = None
                cancelled = False
                for chunk_obj in self.chat_agent.stream_step(
                    messages,
                    tool_registry=registry,
                    settings=settings,
                ):
                    if cancel_event is not None and cancel_event.is_set():
                        cancelled = True
                        break
                    if chunk_obj.chunk:
                        yield {"event": "chunk", "text": chunk_obj.chunk}
                        streamed_any_content = True
                    if chunk_obj.get_finished():
                        assistant_message = chunk_obj.get_finished_chat_message()

                if cancelled:
                    cancel_text = "(cancelled by user)"
                    if assistant_message is None:
                        # Stream was abandoned before any usable content
                        # arrived — synthesize a minimal assistant message
                        # so the SSOT emit path matches the normal
                        # terminal emission.
                        now = datetime.datetime.now()
                        assistant_message = ChatMessage(
                            id=str(uuid.uuid4()),
                            role=ChatMessageRole.Assistant,
                            content=[TextContent(content=cancel_text)],
                            created_at=now,
                            updated_at=now,
                        )
                        agent.chat_history.add_message(assistant_message)
                    else:
                        # Partial content exists.  Append the
                        # cancellation note to whatever was already
                        # streamed — the SSOT now reflects what the user
                        # saw plus the cancellation marker.  The message
                        # is rewritten in place; ``_replace_last_assistant_text``
                        # mutated the chat_history's last ChatMessage
                        # object itself, so we read it back by reference.
                        _replace_last_assistant_text(
                            agent.chat_history,
                            (
                                _message_text(assistant_message).rstrip()
                                + f"\n\n{cancel_text}"
                            ),
                        )
                    yield {
                        "event": "model_message",
                        "role": ASSISTANT_MODEL_ROLE,
                        "payload": chat_message_payload(assistant_message),
                    }
                    return None

                if assistant_message is None:
                    now = datetime.datetime.now()
                    assistant_message = ChatMessage(
                        id=str(uuid.uuid4()),
                        role=ChatMessageRole.Assistant,
                        content=[],
                        created_at=now,
                        updated_at=now,
                    )

                tool_calls = assistant_message.get_tool_calls()
                assistant_text = _message_text(assistant_message).strip()

                if not tool_calls and not assistant_text:
                    if attempt < retry_attempts - 1:
                        logger.warning(
                            "Degenerate empty response with no tool calls "
                            "(attempt %d/%d). Retrying...",
                            attempt + 1,
                            retry_attempts,
                        )
                        continue

                return (assistant_message, streamed_any_content)
            except _BACKEND_CONNECTION_ERRORS as exc:
                if attempt < retry_attempts - 1:
                    logger.warning(
                        "Backend connection error (attempt %d/%d): %s. Retrying...",
                        attempt + 1,
                        retry_attempts,
                        exc,
                    )
                    continue
                logger.warning(
                    "Backend unreachable during turn: model=%s url=%s error=%s",
                    resolved_model,
                    self.provider_config.base_url,
                    exc,
                )
                payload = _backend_unreachable_payload(
                    exc=exc,
                    model=resolved_model,
                    server_url=self.provider_config.base_url,
                    assistant_turns=assistant_turns,
                )
                agent.chat_history.add_assistant_message(payload["assistant_text"])
                yield {
                    "event": "model_message",
                    "role": ASSISTANT_MODEL_ROLE,
                    "payload": chat_message_payload(
                        agent.chat_history.get_messages()[-1]
                    ),
                }
                yield {"event": "final", "result": payload}
                return None
        return None  # pragma: no cover — unreachable; the loop above always returns

    def _dispatch_tools(
        self,
        agent: GrcAgent,
        assistant_message: ChatMessage,
        tool_calls: list[Any],
        registry_builder: ToolAgentsRegistryBuilder,
        active_allowed_tools: set[str],
        *,
        resolved_model: str,
        assistant_turns: int,
        tool_rounds_used: int,
        tool_calls_executed: int,
        failing_call_signatures: dict[tuple[str, str], int],
        streamed_any_content: bool,
    ) -> Generator[dict[str, Any], None, _ToolDispatchOutcome]:
        """Execute one round's tool calls; return counts + loop-stuck state.

        Yields the non-terminal ``assistant_model`` model_message, the
        per-tool ``tool_model`` model_messages, the loop-note
        ``user_model`` model_message when ``_evaluate_loop_state`` returns
        WARN, and on STOP yields the safety-ceiling model_message + final
        then terminates.

        Counter bookkeeping mirrors the original in-line implementation
        exactly (the caller passes the pre-round ``tool_calls_executed``
        and ``tool_rounds_used``; the outcome carries the round delta).
        """
        # Non-terminal round: emit immediately (text is not rewritten).
        yield {
            "event": "model_message",
            "role": ASSISTANT_MODEL_ROLE,
            "payload": chat_message_payload(assistant_message),
        }
        # Surface this round's text (reasoning/think content, or a
        # chatty preamble before the tool call) as soon as it's
        # available, instead of only the terminal round's text.
        if not streamed_any_content:
            round_text = _message_text(assistant_message).strip()
            if round_text:
                yield {"event": "chunk", "text": round_text}

        round_executed = 0
        loop_stuck = False
        for tool_call in tool_calls:
            tool_name = tool_call.tool_call_name
            logger.info(
                "tool_call name=%s args=%s",
                tool_name,
                str(tool_call.tool_call_arguments)[:120],
            )
            delegate = registry_builder.delegates.get(tool_name)
            if delegate is None:
                result = build_error_payload(
                    error_type=ErrorCode.TOOL_NOT_ALLOWED_FOR_SURFACE,
                    message=(
                        f"Tool '{tool_name}' is not available through "
                        "the model-facing surface."
                    ),
                )
                result["tool"] = tool_name
                result["allowed_tools"] = sorted(active_allowed_tools)
                executed = False
            else:
                delegate_result = delegate.invoke(
                    tool_call.tool_call_arguments,
                    allowed_tool_names=active_allowed_tools,
                )
                result = delegate_result.result
                executed = delegate_result.executed
            if executed:
                round_executed += 1
            tool_result_message = _tool_result_message(tool_call, result)
            agent.chat_history.add_message(tool_result_message)
            yield {
                "event": "model_message",
                "role": TOOL_MODEL_ROLE,
                "payload": chat_message_payload(tool_result_message),
            }
            decision = self._evaluate_loop_state(
                tool_name,
                tool_call.tool_call_arguments,
                result,
                executed,
                failing_call_signatures,
            )
            if decision is _LoopDecision.WARN:
                note_msg = ChatMessage.create_user_message(_LOOP_NOTE)
                agent.chat_history.add_message(note_msg)
                yield {
                    "event": "model_message",
                    "role": USER_MODEL_ROLE,
                    "payload": chat_message_payload(note_msg),
                }
            elif decision is _LoopDecision.STOP:
                loop_stuck = True
                break

        if loop_stuck:
            stuck_text = (
                "(stopped: the same tool call failed identically "
                "multiple times in a row)"
            )
            payload = build_error_payload(
                error_type=ErrorCode.SAFETY_CEILING,
                message=(
                    "Stopped: the same tool call failed identically "
                    "multiple times in a row."
                ),
            )
            payload["model"] = resolved_model
            payload["steps"] = assistant_turns
            payload["tool_rounds_used"] = tool_rounds_used
            payload["tool_calls_requested"] = len(tool_calls)
            payload["tool_calls_executed"] = tool_calls_executed + round_executed
            payload["assistant_text"] = stuck_text
            agent.chat_history.add_assistant_message(stuck_text)
            yield {
                "event": "model_message",
                "role": ASSISTANT_MODEL_ROLE,
                "payload": chat_message_payload(
                    agent.chat_history.get_messages()[-1]
                ),
            }
            yield {"event": "final", "result": payload}
            return _ToolDispatchOutcome(
                executed_count=round_executed, loop_stuck=True
            )

        return _ToolDispatchOutcome(
            executed_count=round_executed, loop_stuck=False
        )

    def _run_turn_events(
        self,
        agent: GrcAgent,
        user_message: str,
        *,
        model: str | None,
        max_tool_rounds: int | None,
        on_tool_start: Callable[[str, dict[str, Any]], None] | None,
        on_tool_end: Callable[[str, Any], None] | None,
        cancel_event: threading.Event | None = None,
    ) -> Iterator[dict[str, Any]]:
        # Persist the user message first — before any model / error check —
        # so the prompt is always in the SSOT regardless of what happens next.
        agent.compact_history()
        agent.chat_history.add_user_message(user_message)
        yield {
            "event": "model_message",
            "role": USER_MODEL_ROLE,
            "payload": chat_message_payload(agent.chat_history.get_messages()[-1]),
        }
        agent._turn_user_message = user_message

        resolved_model = model or self.provider_config.model
        if not isinstance(resolved_model, str) or not resolved_model.strip():
            no_model_text = "No model configured."
            agent.chat_history.add_assistant_message(no_model_text)
            yield {"event": "model_message", "role": ASSISTANT_MODEL_ROLE,
                   "payload": chat_message_payload(agent.chat_history.get_messages()[-1])}
            yield {"event": "chunk", "text": no_model_text}
            payload = build_error_payload(
                error_type=ErrorCode.MODEL_NOT_FOUND,
                message=no_model_text,
            )
            payload["model"] = ""
            payload["steps"] = 0
            payload["tool_rounds_used"] = 0
            payload["tool_calls_requested"] = 0
            payload["tool_calls_executed"] = 0
            payload["assistant_text"] = no_model_text
            yield {"event": "final", "result": payload}
            return
        if max_tool_rounds is None:
            max_tool_rounds = MVP_TOOL_SURFACE.default_max_tool_rounds
        if self.provider_config.max_tool_rounds:
            max_tool_rounds = max(max_tool_rounds, self.provider_config.max_tool_rounds)

        tool_calls_executed = 0
        tool_calls_requested = 0
        tool_rounds_used = 0
        assistant_turns = 0
        # Per-signature count of identical failing change_graph calls this turn.
        failing_call_signatures: dict[tuple[str, str], int] = {}

        logger.info("turn_start model=%s message=%s", resolved_model, user_message[:80])
        active_allowed_tools = set(MVP_TOOL_SURFACE.model_tool_names)
        # web_search/web_fetch are Ollama-hosted REST tools. On OpenRouter the
        # `web` plugin grounds the model natively, so those tools are not
        # surfaced (they cannot run against OpenRouter). Backends stay separate.
        if self.provider_config.backend == "openrouter":
            active_allowed_tools -= _OLLAMA_ONLY_TOOLS

        while True:
            # The loop is only bounded by loop/stuck detection (identical repeated calls), not an arbitrary round count.
            settings = self.provider_config.create_settings(
                self.provider,
                tool_choice="auto",
            )
            registry_builder = ToolAgentsRegistryBuilder(
                agent,
                on_tool_start=on_tool_start,
                on_tool_end=on_tool_end,
            )
            registry = registry_builder.build(active_allowed_tools)

            fetched = yield from self._fetch_model_response(
                agent,
                registry,
                settings,
                resolved_model,
                assistant_turns,
                cancel_event=cancel_event,
            )
            if fetched is None:
                return
            assistant_message, streamed_any_content = fetched

            assistant_turns += 1
            tool_calls = assistant_message.get_tool_calls()
            tool_calls_requested += len(tool_calls)

            agent.chat_history.add_message(assistant_message)

            if tool_calls:
                tool_rounds_used += 1
                outcome = yield from self._dispatch_tools(
                    agent,
                    assistant_message,
                    tool_calls,
                    registry_builder,
                    active_allowed_tools,
                    resolved_model=resolved_model,
                    assistant_turns=assistant_turns,
                    tool_rounds_used=tool_rounds_used,
                    tool_calls_executed=tool_calls_executed,
                    failing_call_signatures=failing_call_signatures,
                    streamed_any_content=streamed_any_content,
                )
                if outcome.loop_stuck:
                    return
                tool_calls_executed += outcome.executed_count
                continue

            assistant_text = _message_text(assistant_message)
            if not assistant_text.strip():
                assistant_text = ""
            empty_terminal = not assistant_text
            if empty_terminal:
                assistant_text = _EMPTY_MODEL_RESPONSE_TEXT
            _replace_last_assistant_text(agent.chat_history, assistant_text)
            # Emit the authoritative terminal assistant_model (post-rewrite)
            # so the SSOT row carries the final text the user saw.
            yield {
                "event": "model_message",
                "role": ASSISTANT_MODEL_ROLE,
                "payload": chat_message_payload(
                    agent.chat_history.get_messages()[-1]
                ),
            }
            if empty_terminal:
                logger.warning(
                    "turn_end ok=False empty_model_response steps=%d tool_rounds=%d tool_calls=%d",
                    assistant_turns,
                    tool_rounds_used,
                    tool_calls_executed,
                )
            else:
                logger.info(
                    "turn_end ok=True steps=%d tool_rounds=%d tool_calls=%d",
                    assistant_turns,
                    tool_rounds_used,
                    tool_calls_executed,
                )
            if empty_terminal or not streamed_any_content:
                yield {
                    "event": "chunk",
                    "text": assistant_text,
                }
            final_result: dict[str, Any] = {
                "ok": not empty_terminal,
                "model": resolved_model,
                "steps": assistant_turns,
                "tool_rounds_used": tool_rounds_used,
                "tool_calls_requested": tool_calls_requested,
                "tool_calls_executed": tool_calls_executed,
                "assistant_text": assistant_text,
            }
            if empty_terminal:
                final_result["error_type"] = ErrorCode.EMPTY_MODEL_RESPONSE
            yield {
                "event": "final",
                "result": final_result,
            }
            return


def _function_tool_from_openai_tool(
    schema: dict[str, Any],
    delegate: ToolAgentsToolDelegate,
) -> FunctionTool:
    """Create a FunctionTool while preserving the original OpenAI schema.

    ToolAgents 0.3.0 has a narrow JSON Schema to Pydantic converter. The runtime
    still sends our exact schema to the provider by overriding to_openai_tool.
    """
    compatible_schema = _toolagents_compatible_schema(schema)
    tool = FunctionTool.from_openai_tool(compatible_schema, delegate)
    tool.to_openai_tool = lambda schema=schema: copy.deepcopy(schema)  # type: ignore[method-assign]
    return tool


def _toolagents_compatible_schema(schema: dict[str, Any]) -> dict[str, Any]:
    compatible = copy.deepcopy(schema)
    parameters = compatible.get("function", {}).get("parameters")
    if isinstance(parameters, dict):
        parameters["properties"] = _compatible_properties(parameters.get("properties", {}))
    return compatible


def _compatible_properties(properties: Any) -> dict[str, Any]:
    if not isinstance(properties, dict):
        return {}
    return {
        str(name): _compatible_property_schema(value)
        for name, value in properties.items()
        if isinstance(value, dict)
    }


def _compatible_property_schema(value: dict[str, Any]) -> dict[str, Any]:
    copied = copy.deepcopy(value)
    copied.pop("description", None)
    field_type = copied.get("type", "string")
    if isinstance(field_type, list):
        copied["type"] = _first_supported_schema_type(field_type)
    if copied.get("type") == "array":
        items = copied.get("items")
        if not isinstance(items, dict) or _is_primitive_item_schema(items):
            copied["items"] = {}
        else:
            copied["items"] = _compatible_properties(items)
    elif copied.get("type") == "object":
        copied["properties"] = _compatible_properties(copied.get("properties", {}))
    return copied


def _first_supported_schema_type(values: list[Any]) -> str:
    for value in values:
        if value in {"string", "number", "integer", "boolean", "array", "object"}:
            return str(value)
    return "string"


def _is_primitive_item_schema(items: dict[str, Any]) -> bool:
    return "type" in items and "properties" not in items


def _message_text(message: ChatMessage) -> str:
    parts = [
        content.content
        for content in message.content
        if isinstance(content, TextContent) and isinstance(content.content, str)
    ]
    return "\n".join(part for part in parts if part)


def _tool_result_message(tool_call: ToolCallContent, result: Any) -> ChatMessage:
    now = datetime.datetime.now()
    serialized = (
        result if isinstance(result, str) else json.dumps(result, sort_keys=True, default=str)
    )
    return ChatMessage(
        id=str(uuid.uuid4()),
        role=ChatMessageRole.Tool,
        content=[
            ToolCallResultContent(
                tool_call_result_id=str(uuid.uuid4()),
                tool_call_id=tool_call.tool_call_id,
                tool_call_name=tool_call.tool_call_name,
                tool_call_result=serialized,
            )
        ],
        created_at=now,
        updated_at=now,
    )


def _replace_last_assistant_text(chat_history: ChatHistory, text: str) -> None:
    messages = chat_history.get_messages()
    for index in range(len(messages) - 1, -1, -1):
        if messages[index].role == ChatMessageRole.Assistant:
            new_content = [
                TextContent(content=text) if isinstance(item, TextContent) else item
                for item in messages[index].content
            ]
            if not any(isinstance(item, TextContent) for item in new_content):
                new_content.insert(0, TextContent(content=text))
            messages[index] = ChatMessage(
                id=messages[index].id,
                role=messages[index].role,
                content=new_content,
                created_at=messages[index].created_at,
                updated_at=messages[index].updated_at,
                additional_fields=messages[index].additional_fields,
                additional_information=messages[index].additional_information,
            )
            return


def model_name_matches(name: str, available_ids: list[str]) -> bool:
    """Check if a model name exists in available IDs with :latest suffix tolerance."""
    if name in available_ids:
        return True
    stripped = name.removesuffix(":latest")
    return any(
        id_.removesuffix(":latest") == stripped or id_ == f"{stripped}:latest"
        for id_ in available_ids
    )


__all__ = [
    "GrcOpenAIChatAPI",
    "ToolAgentsLlamaProviderConfig",
    "ToolAgentsRegistryBuilder",
    "ToolAgentsRunner",
]
